"""
Email Report System
Automatically send PDF reports via email
"""

import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders
from pathlib import Path
import os
from datetime import datetime


class EmailReporter:
    """
    Send PDF reports via email
    """
    
    def __init__(self, smtp_server='smtp.gmail.com', smtp_port=587):
        """
        Initialize email reporter
        
        Args:
            smtp_server: SMTP server address
            smtp_port: SMTP port (587 for TLS)
        """
        self.smtp_server = smtp_server
        self.smtp_port = smtp_port
    
    def send_report(self, recipient_email, pdf_path, sender_email=None, 
                   sender_password=None, subject=None, body=None):
        """
        Send PDF report via email
        
        Args:
            recipient_email: Recipient's email address
            pdf_path: Path to PDF file
            sender_email: Sender's email (if None, uses environment variable)
            sender_password: Sender's password (if None, uses environment variable)
            subject: Email subject
            body: Email body text
        
        Returns:
            Dictionary with send status
        """
        # Get credentials from environment if not provided
        if sender_email is None:
            sender_email = os.getenv('BCI_EMAIL_SENDER')
        if sender_password is None:
            sender_password = os.getenv('BCI_EMAIL_PASSWORD')
        
        if not sender_email or not sender_password:
            return {
                'success': False,
                'error': 'Email credentials not provided. Set BCI_EMAIL_SENDER and BCI_EMAIL_PASSWORD environment variables.'
            }
        
        # Create message
        msg = MIMEMultipart()
        msg['From'] = sender_email
        msg['To'] = recipient_email
        
        # Default subject and body
        if subject is None:
            subject = f"BCI Emotion Detection Report - {datetime.now().strftime('%Y-%m-%d')}"
        if body is None:
            body = self._create_default_body()
        
        msg['Subject'] = subject
        
        # Attach body
        msg.attach(MIMEText(body, 'html'))
        
        # Attach PDF
        try:
            pdf_path = Path(pdf_path)
            if not pdf_path.exists():
                return {
                    'success': False,
                    'error': f'PDF file not found: {pdf_path}'
                }
            
            with open(pdf_path, 'rb') as attachment:
                part = MIMEBase('application', 'octet-stream')
                part.set_payload(attachment.read())
            
            encoders.encode_base64(part)
            part.add_header(
                'Content-Disposition',
                f'attachment; filename= {pdf_path.name}'
            )
            
            msg.attach(part)
        
        except Exception as e:
            return {
                'success': False,
                'error': f'Failed to attach PDF: {str(e)}'
            }
        
        # Send email
        try:
            server = smtplib.SMTP(self.smtp_server, self.smtp_port)
            server.starttls()
            server.login(sender_email, sender_password)
            
            text = msg.as_string()
            server.sendmail(sender_email, recipient_email, text)
            server.quit()
            
            return {
                'success': True,
                'message': f'Report sent successfully to {recipient_email}',
                'timestamp': datetime.now().isoformat()
            }
        
        except Exception as e:
            return {
                'success': False,
                'error': f'Failed to send email: {str(e)}'
            }
    
    def _create_default_body(self):
        """Create default HTML email body"""
        return """
        <html>
            <body style="font-family: Arial, sans-serif;">
                <h2 style="color: #3498db;">🧠 BCI Emotion Detection Report</h2>
                
                <p>Dear User,</p>
                
                <p>Please find attached your comprehensive BCI emotion detection session report.</p>
                
                <h3>Report Contents:</h3>
                <ul>
                    <li>Session Summary & Statistics</li>
                    <li>Emotion Distribution Analysis</li>
                    <li>Model Performance Metrics</li>
                    <li>Confidence Timeline</li>
                    <li>Detailed Visualizations</li>
                </ul>
                
                <p>This report was automatically generated by the Senito BCI System.</p>
                
                <hr>
                <p style="color: #7f8c8d; font-size: 0.9em;">
                    <strong>Senito - Emotion-Aware Brain-Computer Interface</strong><br>
                    Advanced EEG-based emotion detection with real-time music adaptation
                </p>
            </body>
        </html>
        """
    
    def send_batch_reports(self, recipients, pdf_path, sender_email=None, 
                          sender_password=None):
        """
        Send report to multiple recipients
        
        Args:
            recipients: List of email addresses
            pdf_path: Path to PDF file
            sender_email: Sender's email
            sender_password: Sender's password
        
        Returns:
            List of send results
        """
        results = []
        
        for recipient in recipients:
            result = self.send_report(
                recipient,
                pdf_path,
                sender_email,
                sender_password
            )
            results.append({
                'recipient': recipient,
                'result': result
            })
        
        return results
    
    def schedule_report(self, recipient_email, pdf_generator_func, 
                       schedule_time, sender_email=None, sender_password=None):
        """
        Schedule a report to be sent at a specific time
        
        Args:
            recipient_email: Recipient's email
            pdf_generator_func: Function that generates the PDF
            schedule_time: datetime object for when to send
            sender_email: Sender's email
            sender_password: Sender's password
        
        Returns:
            Scheduled task information
        """
        import threading
        import time
        
        def send_at_time():
            # Wait until scheduled time
            now = datetime.now()
            wait_seconds = (schedule_time - now).total_seconds()
            
            if wait_seconds > 0:
                time.sleep(wait_seconds)
            
            # Generate PDF
            pdf_path = pdf_generator_func()
            
            # Send email
            result = self.send_report(
                recipient_email,
                pdf_path,
                sender_email,
                sender_password
            )
            
            return result
        
        # Start thread
        thread = threading.Thread(target=send_at_time, daemon=True)
        thread.start()
        
        return {
            'scheduled': True,
            'recipient': recipient_email,
            'schedule_time': schedule_time.isoformat(),
            'thread_id': thread.ident
        }


class ReportScheduler:
    """
    Advanced report scheduling system
    """
    
    def __init__(self, email_reporter):
        self.email_reporter = email_reporter
        self.scheduled_tasks = []
    
    def schedule_daily_report(self, recipient_email, hour=9, minute=0):
        """
        Schedule daily report at specific time
        
        Args:
            recipient_email: Recipient's email
            hour: Hour of day (0-23)
            minute: Minute of hour (0-59)
        
        Returns:
            Task ID
        """
        from datetime import time
        
        task = {
            'id': len(self.scheduled_tasks) + 1,
            'type': 'daily',
            'recipient': recipient_email,
            'time': time(hour, minute),
            'active': True
        }
        
        self.scheduled_tasks.append(task)
        
        return task['id']
    
    def schedule_weekly_report(self, recipient_email, day_of_week=0, 
                              hour=9, minute=0):
        """
        Schedule weekly report
        
        Args:
            recipient_email: Recipient's email
            day_of_week: Day of week (0=Monday, 6=Sunday)
            hour: Hour of day
            minute: Minute of hour
        
        Returns:
            Task ID
        """
        from datetime import time
        
        task = {
            'id': len(self.scheduled_tasks) + 1,
            'type': 'weekly',
            'recipient': recipient_email,
            'day_of_week': day_of_week,
            'time': time(hour, minute),
            'active': True
        }
        
        self.scheduled_tasks.append(task)
        
        return task['id']
    
    def cancel_task(self, task_id):
        """Cancel a scheduled task"""
        for task in self.scheduled_tasks:
            if task['id'] == task_id:
                task['active'] = False
                return True
        return False
    
    def get_active_tasks(self):
        """Get list of active scheduled tasks"""
        return [t for t in self.scheduled_tasks if t['active']]
